### ISSUE TITLE
Does this module support running in cluster mode with more than one task?

### ISSUE THREAD

**Issue by marcossv9** [everest-engineering/terraform-aws-mongodb-ecs#3]
Hi,
I couldn't find explicit information about this module saying it does support running more than one task in mongo cluster mode..
Can you tell me if it is supported?
Thanks.
Regards,

**Comment by prasanna214** [comment]
Hello @marcossv9 
 
This module is a basic single node implementation of Mongo on ECS. Currently, there is no support for running more than one Mongo task on the cluster. 

Thanks & Regards
